name: Build Jetson Image

on:
  push:
    branches:
      - main
      - master


env:
  SOURCE_DATE_EPOCH: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman just jq qemu-user-static

      - name: Build Root Filesystem
        run: just build-jetson-rootfs 24.04

      - name: Build Jetson Image
        run: just build-jetson-image -b jetson-orin-nano -d SD -l 36

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jetson-image
          path: jetson.img
